"""create first table

Revision ID: 88a1ff92106b
Revises: 3b123dcdb50f
Create Date: 2019-04-09 21:50:32.964849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a1ff92106b'
down_revision = '3b123dcdb50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
